export const grammarTypeEnum = [
  'verb',
  'noun',
  'adjective',
  'adverb',
  'pronoun',
  'preposition',
  'conjunction',
  'interjection',
  'sentence structure',
  'tense',
  'clause',
  'phrase',
  'article',
  'modal',
  'punctuation',
  'other',
];

export const lessonTypeEnum = [
  'grammar',
  'vocabulary',
  'idioms',
  'phrases',
  'conversation',
  'listening',
  'reading',
  'writing',
  'speaking',
  'pronunciation',
  'culture',
  'exam preparation',
  'other',
];